[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "UniGui"
authors = [{name = "Marc A. Champlain", email = "email@mchamplain.com"}]
dynamic = ["version", "description"]
